# Markdownlint configuration for commit-wizard
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD029/ol-prefix - Ordered list item prefix
MD029: false

# MD034/no-bare-urls - Bare URL used
MD034: false

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements:
    - "br"
    - "details"
    - "summary"
    - "kbd"
    - "sup"
    - "sub"
    - "div"
    - "img"

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: fenced

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2
  # Spaces for first level
  start_indented: false
