codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 38% # Minimum 38% coverage (current: 38.12%)
        threshold: 2% # Allow 2% drop before failing
        if_ci_failed: error

    patch:
      default:
        target: 30% # Require 30% coverage on changed lines
        threshold: 5% # Allow 5% below target
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

ai:
  enabled: true
  coverage_analysis:
    enabled: true
  test_suggestions:
    enabled: true

ignore:
  - "target/" # Build artifacts
  - "src/main.rs" # CLI entry point - external interaction
  - "src/ui.rs" # Terminal UI - requires terminal/human interaction
