#!/bin/bash
# Create Alpine package info file (.PKGINFO)

VERSION=$1
ARCH=$2

if [ -z "$VERSION" ] || [ -z "$ARCH" ]; then
    echo "Usage: $0 <version> <arch>" >&2
    exit 1
fi

# Get build date
BUILDDATE=$(date -u +%s)

# Get package size (will be calculated after files are in place)
SIZE=$(du -sb pkg 2>/dev/null | cut -f1 || echo "0")

cat <<EOF
# Generated by commit-wizard build system
pkgname = commit-wizard
pkgver = ${VERSION}
pkgdesc = A CLI tool to help create better commit messages
url = https://github.com/jfheinrich-eu/commit-wizard
builddate = ${BUILDDATE}
packager = jfheinrich <joerg@jfheinrich.eu>
size = ${SIZE}
arch = ${ARCH}
license = MIT
depend = git
depend = libgcc

# Runtime dependencies
# git - Required for repository operations
# libgcc - Required for Rust runtime
# Optional: bash-completion for shell completions
EOF
